{% set name = "rdkit" %}
{% set version = "2018.03.2" %}
{% set filename = "Release_%s.tar.gz" % version.replace(".", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn:  {{ filename }}
  url: https://github.com/rdkit/rdkit/archive/{{ filename }}
  sha256: 29eeba93e723f0f9d61e31cf0f89ec18ba942a7f9e416dbc1a92122fce08cbed
  patches:
    - vs2015.patch  # [win and py>=35]

build:
  number: 0
  skip: true  # [win and py27]

requirements:
  build:
    - {{ compiler('cxx') }}  # [not osx]
    - clang_osx-64  # [osx]
    - clangxx_osx-64  # [osx]
    - cmake
    - requests
    - jom  # [win]
    - pkg-config  # [not win]
  host:
    - cairo
    - boost
    - eigen
    - freetype
    - python
    - numpy
    - pillow
    - pandas
  run:
    - {{ pin_compatible('boost', max_pin='x.x.x') }}
    - {{ pin_compatible('cairo') }}
    - python
    - pillow
    - pandas
    - {{ pin_compatible('numpy') }}
    - pycairo
    - six

test:
  imports:
    - rdkit
    - rdkit.Avalon
    - rdkit.Chem
    - rdkit.Chem.AllChem
    - rdkit.DataManip
    - rdkit.Dbase
    - rdkit.DistanceGeometry
    - rdkit.ForceField
    - rdkit.Geometry
    - rdkit.ML
    - rdkit.Numerics
    - rdkit.SimDivFilters
    - rdkit.VLib
    - rdkit.VLib.NodeLib

about:
  home: http://rdkit.org
  license: BSD 3-Clause
  license_file: license.txt
  summary: 'RDKit is a collection of cheminformatics and machine-learning software written in C++ and Python.'

extra:
  recipe-maintainers:
    - pstjohn
    - mcs07
