{% set name = "rdkit" %}
{% set version = "Release_2017_09_3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/rdkit/rdkit/archive/{{ version }}.tar.gz
  sha256: 6a4d9e9eb0ca06cbcdc20505f0c6ea0b1167b4dcdf7d1185871ba16ce701a5f4

build:
  skip: true  # [win]
  number: 2

requirements:
  build:
    - toolchain
    - cmake
    - requests
    - boost 1.66.0
    - python
    - numpy 1.11.*
    - pillow
    - freetype 2.8.1
    - eigen
    - pandas
    - cairo 1.14.*
    - jom  # [win]
    - pkg-config  # [not win]
  run:
    - cairo 1.14.*
    - boost 1.66.0
    - python
    - six
    - numpy >=1.11

test:
  imports:
    - rdkit
    - rdkit.Avalon
    - rdkit.Chem
    - rdkit.Chem.AllChem
    - rdkit.DataManip
    - rdkit.Dbase
    - rdkit.DistanceGeometry
    - rdkit.ForceField
    - rdkit.Geometry
    - rdkit.ML
    - rdkit.Numerics
    - rdkit.SimDivFilters
    - rdkit.VLib
    - rdkit.VLib.NodeLib

about:
  home: http://rdkit.org
  license: BSD 3-Clause
  license_file: license.txt
  summary: 'RDKit is a collection of cheminformatics and machine-learning software written in C++ and Python.'

extra:
  recipe-maintainers:
    - pstjohn
