travis:
  secure:
    BINSTAR_TOKEN: jmcQpZspqPETRcpW0uD2ZkgM2335d+xCu06AiN4sAEcoiEvg85Rhfse3A6j0NRpt2mKR/0P7Sxlk0TkDiUfYbNw9U33QYDIa3LxA6mu0q36+J5uC2Xp8tmDvVFm/QoSmkzQLtGI9kdqCcLX7RzS+Qs7OKbvEV5uHuBof1ztAoqDjadSCVhjHc+H+A0I0nj6TOAqCR7W9wrPzOfXh7HsT7QuVPlSHQS0dymMw70WO7ShKuXXdGDQn5LCokSEWotN0ZQN4Nqg8E+q3UHrtnpfBWPll0BulrKutJoGgqxr5KU2CIUS4LXUUwlfsc3XYrsc+SoIHHOAPUgcOO8IU59GODI4f/l6ydBVus8MYFG3KOlrDxsu1cPN9zv/DnnZo6LQv7ZwGUlpAT4MHRZYQa8doUDfs37xoBi47n2H2/gyURH/NMBH1oxt++aaqPfqjSxtbBOK4ILZNGoDKBLsIV2T6KIHKOCCkTN41+CJGf+9HLNaNun40OwNnM5uzrFUVqBDE64W5PMZa1QqwKvB2cVCueyZD0ZFDi2ORRhRlpPrt8JMwerAuEaowMaxZdOu9GwxFBXqqRz1CUa9xECMs+PCO+CCq0ylEdTG4+sP54cwwxNQC+Kul4AhZJ811pK6F1o98whs6sRoJAjx3oBaDIh1xmlZGUEADJIsjgkbvGlWB6fM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
