travis:
  secure:
    BINSTAR_TOKEN: Thp7EI1uH2PB3nrZyGjwt/1SVVWExJsBwQ2cahTFRjvaMFTal9tm2vd6r1L5m43CrvU3upEoq4kbjU4+BG3WJ25mtwci1sRJKnx8KtT+jbPsVzpHrHwlqY4IEh/5f6YahofH5aOWymYW1fCFiNw/ZasHSg0yRf70VjRBw6EsFu2GUvait7A8U9xKz1J4WbTYzQ1UtnS+za946HQR38yI/YKS8pa8UOgsWg8KIuujq+l143rRXDkEk1tl07xQUVBSnkwpAq3fs3lUVG2RvAzAolj8kzrg0bkPnWAhI5T9/Oww54t0PEsDPnXUCuTYGTxWLdfLb+3NhY1WPrCv58n1yIX+81EbAosr0I9cu1HIVbwFE+h9NxcT2cgbQgAUhzprNuYIWaNwwhsbhL5UBB7iVIk1/YBeyzahvee2UDakR5eMccDBHKT0bs31K3BF6pxrVeTAxCJtpnCc6J1Fwnr9g28jyPK9OEvwbJShaxyA9rHwh98/BWVBIr5vgs41L9qgMbZp9A3xVdzgU5iZennbsDGFM6RfrpNyl35b1eVcf2QTHUZvKuS58D01IG88WGdeqwAMwX1RqWcSclgZSVe1md/WrJn8ThKAtmNafJORxJbcMEOV8CqK2q2Uxf7t8ENQpkNPPnhHJcO8Qz+qjFNpAeGLC0y2kAJakzjj6Sb6muQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
