travis:
  secure:
    BINSTAR_TOKEN: MreTwweIKnqpYUec+GD6Hu8LhFMIj7c9TkSq55S1bkVt5G/oTnK0gXy2FKX8gLVXi9wSfYLGPdQENh9f/dI6FEOqixBpc8kTVq5fkwf9ncXEgr0MgUcV7vfRvOyTRvpjHOXtWxiM+yZ+1qKJRqlIQvSiiO4PNJtmJ35163SfDg6Me7v2dT4HGov6Rv5tZC3EJS1GKe8txJMf2tP22SNeq9gVlOHw9olF2jL011ee3w6TZ34piHRry3FLg/TBfATP3an8Ir1df4UpwlEjWOtBMzaLikXuDVj0aIP4EzR+I/z5g3h0y9mOP1CTHZJDyoMNw14H5V/rh2vB8gBVzJj0K6hEiB6MrJptQ4TqVdLjG1F//LamUjU/FdMKT5GXiOXQWSsgDWCWxAbef4ryBPliwn2Tmuac87O5bZe4HhdO+KzMiATpR2s+s/nSFbLFPPw8UDSR7mh13SVKFRvkmW6GvgnBaeNXDN1VRW1gWLd/5HahTi1REyhmzfKFNpqI3A7I0LnsGQ4talD8USnI1LGxn070kOA54ImAfM9UKm/2pZOoLz2Y4lHIYjKKtcOhsB4sal2U7Rf24/T6a4uH6DBrKtLpUanOhczUaJrn0WiulIPwqXRP2nqzFr/dOW21WjphRqn6eGzJPDMuRPWSnu7GBxvaOB3mXOz1ZXiFNayON/0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
