travis:
  secure:
    BINSTAR_TOKEN: I4whDRR2yK5I61eimH8oT0q+rMs4mfw40qsiUep1kYpChkSoDlCCwKJ6R4xHAZaUQi634hXbjVfAm1O9nTZGA0J66J5uLNsILzJVwsf9JE8c3B1hrEjY+cRrhBplaSHVqHUpw530Q40ONZAFUblD6u8PuQHXWPIg+TK4tEwqqs1qo+VkTDPeDzlVcA2MyWacywdZHn0O7bm+X7QkfOW5xqt/orq7d0ZctTvwqHmDCpZ5ACD4QqdJNOqY9DIw9xs1rsaOS9jqHSK4grRhXeJfKrqgxHEkJaiaUKwufE+540Ly2bgi8oTiw/0FttxZpd816kw7Vjb/UgRCsBCmJIYgt7/8UGCRKUOSn+DwIBcEqG6PVelI4etIqPFjMP2KKCjFKxZm80sWgsFspg9V05GlTs/S8xKT5dfPp9U6KL+JTn/vY+HxsAa1U3HrjaTqHxGOLTpw7D0QFdommIJoPUbx1lVSkdC7uvKMrczFM06ZlF7SFG3UH6DfHZWVd7qJtqj9y9Em1bwICFcspqxkT0JnnwgkxmTZk/iTFQiWTfQcAYtIADeXs5ZubEKJ4OXmgs7Lag8h/TBpRYuXiKOnhoYBW2HPMOplMV3BAtxFC0S2x84S5PCbMEPppP17tBvlYoBlKj/mjhNoY6Wt5YRwgErBU0bhoIp8Y+l+QeBOsxYqYZs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
